name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go 1.22
        run: |
          wget https://golang.org/dl/go1.22.3.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz
          echo 'export PATH=$PATH:/usr/local/go/bin' >> $GITHUB_ENV
          echo 'export GOTOOLCHAIN=go1.22.3' >> $GITHUB_ENV
          source $GITHUB_ENV
          go version

      - name: Install dependencies
        run: /usr/local/go/bin/go mod tidy

      - name: Build binary
        run: |
          mkdir -p build-artifacts-${{ github.run_id }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} /usr/local/go/bin/go build -o build-artifacts-${{ github.run_id }}/kollect ./cmd/kollect

      - name: List build-artifacts directory
        run: ls -la build-artifacts-${{ github.run_id }}

      - name: Copy additional files
        run: |
          cp LICENSE README.md build-artifacts-${{ github.run_id }}/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build-artifacts-${{ github.run_id }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}