# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goos: darwin
            goarch: "386"
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List repository contents
        run: ls -la

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build binary
        run: |
          mkdir -p build-artifacts-${{ github.run_id }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build-artifacts-${{ github.run_id }}/kollect ./cmd/kollect

      - name: List build-artifacts directory before copying files
        run: ls -la build-artifacts-${{ github.run_id }}

      - name: Copy additional files
        run: |
          cp -r ./LICENSE ./README.md ./build-artifacts-${{ github.run_id }}/

      - name: List build-artifacts directory after copying files
        run: ls -la build-artifacts-${{ github.run_id }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build-artifacts-${{ github.run_id }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}