# .github/workflows/release.yaml

name: Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: |
          mkdir -p build-artifacts-${{ github.run_id }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build-artifacts-${{ github.run_id }}/kollect ./cmd/kollect

      - name: List build-artifacts directory
        run: ls -la build-artifacts-${{ github.run_id }}

      - name: Copy additional files
        run: |
          cp LICENSE README.md build-artifacts-${{ github.run_id }}/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: build-artifacts-${{ github.run_id }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}